@c Copyright (C) 1988-2018 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node Contributing
@chapter GCCの開発に貢献する

GCCのリリースがうまく動作することを確認するために、GCCのリリースを事前に助けたいのであれば、現在の開発ソースはSVNから入手できる（@uref{http://gcc.gnu.org/svn.html}参照）。 ソースとバイナリのスナップショットはFTPでも利用できる。 @uref{http://gcc.gnu.org/snapshots.html}を参照。。

GCCの改善に取り組みたい場合は、次のURLのアドバイスを読んでください：

@smallexample
@uref{http://gcc.gnu.org/contribute.html}
@uref{http://gcc.gnu.org/contributewhy.html}
@end smallexample

@noindent
有益な貢献をし、重複した作業を避ける方法については、 提案されたプロジェクトは@uref{http://gcc.gnu.org/projects/}.
