@c Copyright (C) 2009-2017 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node C++ Implementation
@cindex implementation-defined behavior, C++ language



@menu
@end menu



@itemize @bullet
@item


@end itemize


@itemize @bullet
@item


@end itemize
