@c Copyright (C) 1988-2020 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node Service
@chapter GCCの助けを得る方法

GCCのインストール、使用、または変更に関するヘルプが必要な場合は、見つける方法が2つある。

@itemize @bullet
@item
適切なネットワークメーリングリストにメッセージを送信する。まず、@email{gcc-help@@gcc.gnu.org} （GCCのインストールや使用に関するヘルプ）を試すこと。応答がない場合は、@email {gcc@@gcc.gnu.org}を試してみる。 GCCの変更については、@email{gcc@@gcc.gnu.org}に尋ねること。 GCCのバグを発見したと思われる場合は、@pxref{Bug Reporting}の指示に従って報告すること。

@item
手数料を払って手伝ってくれる人がいるかどうかサービスディレクトリを調べてること。サービスディレクトリは@uref{http://www.fsf.org/resources/service}.
@end itemize

詳細は、次を参照せよ。@uref{http://gcc.gnu.org/faq.html#support}.
